name: 'Lint and Format Check'
description: 'Run ESLint and check code formatting with Prettier'

runs:
  using: 'composite'
  steps:
    - name: Run ESLint
      shell: bash
      run: npm run lint

    - name: Check code formatting
      shell: bash
      run: npm run format -- --check
